### ISSUE TITLE
Make Net Carb Handling Optional

### ISSUE THREAD

**Issue by LohikaarmeVaeltaja** [Surye/mfp-keto-userscript#39]
Diary:
http://www.myfitnesspal.com/food/diary/lohikaarme_vaeltaja

http://www.myfitnesspal.com/food/diary/lohikaarme_vaeltaja?date=2017-08-28
See the Mocha Chip entry

http://www.myfitnesspal.com/food/diary/lohikaarme_vaeltaja?date=2017-08-24
Similar issue here with the Simple Truth ice cream

**Comment by Surye** [comment]
This is correct, food entries marked as Net Carbs are expected to already be Net Carbs. This is a data issue.

**Comment by LohikaarmeVaeltaja** [comment]
Oh, so there's no way to toggle this feature on or off?  I often find/seek out/input the "net carbs" entries because those ones already subtract sugar alcohol (but not fiber).

**Comment by Surye** [comment]
No, this was one reason I didn't want to support the concept of net carbs, because the data is inconsistent and troublesome. Most "Net Carb" entries are really "Net Carbs", if they say net carbs but include fiber, they are categorically wrong, and I can't fix that. I can look into options and/or a forked version, but it may take some time for me to have the time for that. Sorry!
