### ISSUE TITLE
Some items show total carbs rather than net carbs

### ISSUE THREAD

**Issue by jpschewe** [Surye/mfp-keto-userscript#42]
In the attached screenshot it seems that the first item of a meal shows total carbs rather than net carbs. I'm using tampermonkey with chrome on Linux.
![screenshot from 2017-12-06 05-50-07](https://user-images.githubusercontent.com/226585/33660472-84324952-da49-11e7-8b0d-b7894b0158f0.png)

**Comment by jpschewe** [comment]
I see the same thing using tampermonkey on Firefox 57.

**Comment by Surye** [comment]
https://github.com/Surye/mfp-keto-userscript/pull/31

This is somewhat a data issue, if the item says "Net Carbs" it's assumed it's already net carbs because a lot of entries in MFP are put in that way. In this case the tortillas are not net carbs, the name just includes them. I am going to the of the best fix here...

**Comment by jpschewe** [comment]
OK, so I should use a different entry that doesn't say "net carbs" in it if I'm going to use one that is showing total carbs. Is that correct?

**Comment by Surye** [comment]
That is the easiest solution you can do, yea. I may change the design but
in the mean time that would do it.

**Comment by jpschewe** [comment]
Although as I look closer at the data, the net carbs total value at the bottom doesn't follow this rule, it just subtracts the total fiber from the total gross carbs.

**Comment by Surye** [comment]
There was a bug where the total wasn't tracking the "already included fiber" from "net carb" food entries. It should be fixed now.
