### ISSUE TITLE
Net Carb Calculation at Bottom not adding corectly

### ISSUE THREAD

**Issue by scotprice** [Surye/mfp-keto-userscript#43]
I am writing to report that when the calculations of total net carbs are done at the bottom, they arent calculating the total correctly.  Total Net Carbs seem to be missing a few items.

**Comment by ADevsBestFriend** [comment]
Reporting this issue as well.
![2017-12-11_10-06-54](https://user-images.githubusercontent.com/34452542/33840776-8400f7a6-de5b-11e7-8011-c15319556887.png)

**Comment by vcastellano-spl** [comment]
For both of you, do you have items that say "Net Carbs" in the title?

**Comment by Surye** [comment]
For both of you, do you have items that say "Net Carbs" in the title?

**Comment by lawless01** [comment]
Same issue. "Net Carbs" is in the title.
![image](https://user-images.githubusercontent.com/36042484/35684394-c102eb80-0734-11e8-9480-5661f188294b.png)

![image](https://user-images.githubusercontent.com/36042484/35684354-9fc53cac-0734-11e8-9976-09a0f505f452.png)

**Comment by Trotzali** [comment]
I am also having the same issue.  Not carbs at the bottom not adding up in the Totals row. Remaining row looks ok but Total is out
<img width="364" alt="screen shot 2018-03-08 at 8 12 38 pm" src="https://user-images.githubusercontent.com/37175218/37142778-29b97bdc-230d-11e8-8c6a-84e204fee32a.png">

**Comment by ghost** [comment]
Hi there,

I was having the same issue - Total Net Carbs at the bottom was wrong. So I tasked a friend with fixing the code, and it now works. In the total row at the bottom, instead of subtracting fibre from carbs, which is wrong because in some cases we don't want to subtract the fibre, it now simply adds the net carbs together.

Happy to share the modified file if anyone is interested.

Cheers,

Paul

**Comment by Surye** [comment]
There was a bug where the total wasn't tracking the "already included fiber" from "net carb" food entries. It should be fixed now.
